SELECT
    L."KEY", L."SCH_KEY", L."NAME", L."SAVE_WAY", L."GUIDE", L."OS_TYPE", L."REJOIN_TYPE",
    L."CONTRACT_PRICE", L."START_DATE", L."END_DATE", L."START_QUARTER", L."START_TIME", S."ADS_SHAPE" AS "SHAPE"
FROM {{ref('CLEAN_LIST')}} AS L
INNER JOIN {{source('s3_raw_data', 'IVE_SHAPE_MANUAL')}} AS S ON L."SAVE_WAY"=S."ADS_SAVE_WAY"