SELECT
    Y."KEY", Y."DATE", Y."TIME", Y."MDA", Y."TIME_CLK", Y."TIME_TURN",
    Y."ADV_COST", Y."REWARD_COST", Y."MDA_COST", Y."CVR", Y."1000_W_EFFICIENCY",
    L."SCH_KEY", L."NAME", L."SAVE_WAY", L."GUIDE", L."OS_TYPE", L."REJOIN_TYPE",
    L."CONTRACT_PRICE", L."START_DATE", L."END_DATE", L."START_QUARTER", L."START_TIME", L."SHAPE",
    S."RPT_TYPE", S."MDA_ARR", S."TURN_GOAL", S."TURN_REAL"
FROM {{ref('CLEAN_YEAR')}} AS Y
LEFT JOIN {{ref('CLEAN_LIST_SHAPE')}} AS L ON Y."KEY"=L."KEY"
LEFT JOIN {{ref('CLEAN_SCH')}} AS S ON L."SCH_KEY"=S."SCH_KEY"
WHERE
    Y."TIME_CLK" IS NOT NULL AND Y."TIME_TURN" IS NOT NULL AND Y."ADV_COST" IS NOT NULL AND Y."1000_W_EFFICIENCY" IS NOT NULL
    AND L."NAME" IS NOT NULL AND L."SAVE_WAY" IS NOT NULL AND L."GUIDE" IS NOT NULL
    AND L."OS_TYPE" IS NOT NULL AND L."REJOIN_TYPE" IS NOT NULL AND L."START_QUARTER" IS NOT NULL AND L."START_TIME" IS NOT NULL
    AND S."RPT_TYPE" IS NOT NULL AND S."TURN_GOAL" IS NOT NULL
ORDER BY Y."DATE" DESC, Y."TIME" DESC