SELECT
    A."KEY", A."DATE", A."TIME", A."MDA", A."TIME_CLK", A."TIME_TURN",
    A."ADV_COST", A."REWARD_COST", A."MDA_COST", A."CVR", A."1000_W_EFFICIENCY",
    A."SCH_KEY", A."NAME", A."SAVE_WAY", A."GUIDE", A."OS_TYPE", A."REJOIN_TYPE",
    A."CONTRACT_PRICE", A."START_DATE", A."END_DATE", A."START_QUARTER", A."START_TIME", A."SHAPE",
    A."RPT_TYPE", A."MDA_ARR", A."TURN_GOAL", A."TURN_REAL", I."INDUSTRY"
FROM {{ref('IVE_ANALYTICS_DATA')}} AS A
INNER JOIN {{source('s3_mapping_data','IVE_INDUSTRY_MAPPING')}} AS I ON A."NAME"=I."NAME"
WHERE
    A."TIME_CLK" IS NOT NULL AND A."TIME_TURN" IS NOT NULL AND A."ADV_COST" IS NOT NULL
    AND A."NAME" IS NOT NULL AND A."SAVE_WAY" IS NOT NULL AND A."GUIDE" IS NOT NULL
    AND A."OS_TYPE" IS NOT NULL AND A."REJOIN_TYPE" IS NOT NULL AND A."START_QUARTER" IS NOT NULL AND A."START_TIME" IS NOT NULL
    AND A."RPT_TYPE" IS NOT NULL AND A."TURN_GOAL" IS NOT NULL
ORDER BY A."DATE" DESC, A."TIME" DESC