COPY INTO 's3://ivekorea-airflow-practice-taeeunk/ive_analytic/IVE_ANALYTICS_FINAL.parquet'
FROM (
  SELECT 
    "KEY" AS "KEY",
    "DATE" AS "DATE",
    "TIME" AS "TIME",
    "MDA" AS "MDA",
    "NAME" AS "NAME",
    "SAVE_WAY" AS "SAVE_WAY",
    "GUIDE" AS "GUIDE",
    "OS_TYPE" AS "OS_TYPE",
    "REJOIN_TYPE" AS "REJOIN_TYPE",
    "SHAPE" AS "SHAPE",
    "RPT_TYPE" AS "RPT_TYPE",
    "MDA_ARR" AS "MDA_ARR",
    "START_QUARTER" AS "START_QUARTER",
    "START_TIME" AS "START_TIME",
    "START_DATE" AS "START_DATE",
    "END_DATE" AS "END_DATE",
    "INDUSTRY" AS "INDUSTRY",
    CAST("TIME_CLK" AS FLOAT) AS "TIME_CLK",
    CAST("TIME_TURN" AS FLOAT) AS "TIME_TURN",
    CAST("ADV_COST" AS FLOAT) AS "ADV_COST",
    CAST("REWARD_COST" AS FLOAT) AS "REWARD_COST",
    CAST("MDA_COST" AS FLOAT) AS "MDA_COST",
    CAST("CVR" AS FLOAT) AS "CVR",
    CAST("ABS" AS FLOAT) AS "ABS",
    CAST("1000_W_EFFICIENCY" AS FLOAT) AS "1000_W_EFFICIENCY",
    CAST("CONTRACT_PRICE" AS FLOAT) AS "CONTRACT_PRICE",
    "SCH_KEY" AS "SCH_KEY",
    "LIMIT_TYPE" AS "LIMIT_TYPE"
  FROM IVE_DATA.MAPPING_DATA.IVE_ANALYTICS_MAPPING_DATA
)
STORAGE_INTEGRATION = s3_int_taeeun
FILE_FORMAT = (
    TYPE = PARQUET
    COMPRESSION = SNAPPY
)
SINGLE = TRUE
MAX_FILE_SIZE = 5368709120
OVERWRITE = TRUE;