COPY INTO 's3://ivekorea-airflow-practice-taeeunk/ive_analytic/IVE_ANALYTICS_FINAL.csv'
FROM IVE_DATA.MAPPING_DATA.IVE_ANALYTICS_MAPPING_DATA
STORAGE_INTEGRATION = s3_int_taeeun
FILE_FORMAT = (
    TYPE = CSV
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    COMPRESSION = NONE
    NULL_IF = ('\\N')
    EMPTY_FIELD_AS_NULL = False
)
HEADER = TRUE
SINGLE = TRUE
MAX_FILE_SIZE = 5368709120
OVERWRITE = TRUE;